### POST a new room
POST http://localhost:3000/room

### GET a room
GET http://localhost:3000/room/XNXX1

### PATCH update room
PATCH http://localhost:3000/room/XNXX1
Content-Type: application/json

{
  "name": "Decent room name",
  "endDate": "01/01/2023"
}

### PUT start game
PATCH http://localhost:3000/room/XNXX1
Content-Type: application/json

{
  "status": "IN_GAME"
}

### GET all players in room
GET http://localhost:3000/room/XNXX1/players

### PATCH admin (kick player from room)
PATCH http://localhost:3000/room/M22B9/player/70/admin
Content-Type: application/json

{
  "roomCode": null
}

### DELETE room
DELETE http://localhost:3000/room/XNXX1
