version: '3'
services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: {}
