### POST player without existing room (will be admin)
POST http://localhost:3000/player
Content-Type: application/json

{
  "name": "Lucky"
}

### POST player with existing room
POST http://localhost:3000/player
Content-Type: application/json

{
  "roomCode": "XNXX1",
  "name": "Arty"
}

### PUT update for a player
PUT http://localhost:3000/player
Content-Type: application/json

{
  "id": 16,
  "name": "Arty",
  "passcode": "1234"
}

### POST getMyPlayer
POST http://localhost:3000/player/my-player
Content-Type: application/json

{
  "name": "Arty",
  "passcode": "1234",
  "roomCode": "XNXX1"
}

### GET current player in session
GET http://localhost:3000/player/me
