### POST a new mission
POST http://localhost:3000/mission
Content-Type: application/json

{
  "content": "Push your friend in the stairs 2"
}

### GET missions of player
GET http://localhost:3000/mission/player

### GET count of missions in Room
GET http://localhost:3000/mission/room

### PATCH mission
PATCH http://localhost:3000/mission/1
Content-Type: application/json

{
  "content": "New Mission"
}

### DELETE mission
DELETE http://localhost:3000/mission/4
