name: Deploy
on:
  push:
    branches:
      - master
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "killer-api-demo" #Must be unique in Heroku
          heroku_email: "arthurjcq@hotmail.fr"

      - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build API
        run: yarn build

      - name: Execute migration
        run: knex migrate:latest
